# Generated by Django 5.0.3 on 2024-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='Buyer_id',
            new_name='buyer_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=15),
        ),
    ]
